jax:
  url: https://github.com/google/jax.git
  tracking_ref: main
  latest_verified_commit: 7852045582d92b5e3b3b7af58f2a99a06decf1c9
  mode: git-clone
xla:
  url: https://github.com/openxla/xla.git
  tracking_ref: main
  latest_verified_commit: 4ef02f7522f80d8a5299b5bfb1e5ccb493cc1980
  mode: git-clone
flax:
  url: https://github.com/google/flax.git
  mirror_url: https://github.com/nvjax-svc-0/flax.git
  tracking_ref: main
  latest_verified_commit: 1961c1259e6c2d22a0c27de9599476aaa073a553
  mode: git-clone
  patches:
    pull/3340/head: file://patches/flax/PR-3340.patch # Add Sharding Annotations to Flax Modules
transformer-engine:
  url: https://github.com/NVIDIA/TransformerEngine.git
  tracking_ref: main
  latest_verified_commit: a65ad37e622ad89837b15520b9f2b6c7232d3423
  mode: git-clone
t5x:
  url: https://github.com/google-research/t5x.git
  mirror_url: https://github.com/nvjax-svc-0/t5x.git
  tracking_ref: main
  latest_verified_commit: 5f03619b0c5ebb44ae6adde1a2d8eea1a4b55fe0
  mode: git-clone
  patches:
    mirror/patch/partial-checkpoint-restore: file://patches/t5x/mirror-patch-partial-checkpoint-restore.patch # pull/1392/head  # https://github.com/google-research/t5x/pull/1392: Add support for partial checkpoint restore
    mirror/patch/dali-support: file://patches/t5x/mirror-patch-dali-support.patch # pull/1393/head  # https://github.com/google-research/t5x/pull/1393: Adds DALI support to t5x
    mirror/patch/t5x_te_in_contrib_noindent: file://patches/t5x/mirror-patch-t5x_te_in_contrib_noindent.patch # pull/1391/head  # https://github.com/google-research/t5x/pull/1391: Adds transformer engine support and GPU optimizations to T5x (enables H100)
paxml:
  url: https://github.com/google/paxml.git
  mirror_url: https://github.com/nvjax-svc-0/paxml.git
  tracking_ref: main
  latest_verified_commit: e0466ca220f494ff8bb003ff4b0bce99c17a407e
  mode: git-clone
  patches:
    pull/46/head: file://patches/paxml/PR-46.patch # adds Transformer Engine support
praxis:
  url: https://github.com/google/praxis.git
  mirror_url: https://github.com/nvjax-svc-0/praxis.git
  tracking_ref: main
  latest_verified_commit: 0350fa01cf40e8cdb3f12feb1354055b6dc14215
  mode: git-clone
  patches:
    pull/27/head: file://patches/praxis/PR-27.patch # This PR allows XLA:GPU to detect the MHA pattern more easily to call fused kernels from cublas.
    pull/36/head: file://patches/praxis/PR-36.patch # adds Transformer Engine support
lingvo:
  # Used only in ARM pax builds
  url: https://github.com/tensorflow/lingvo.git
  tracking_ref: master
  latest_verified_commit: 84ee9fad74f39f8bd7b9cc34a69d501512026f73
  mode: git-clone
tensorflow-text:
  # Used only in ARM pax and t5x builds
  url: https://github.com/tensorflow/text.git
  tracking_ref: v2.13.0
  latest_verified_commit: 917a681d7220ebf9b62a08b6f9ce7b7db886ddef
  mode: git-clone
pydantic:
  version: X.Y.Z
  mode: pip-constraint
# Used by praxis
fiddle:
  url: https://github.com/google/fiddle.git
  tracking_ref: main
  latest_verified_commit: 439c0e94cc49bcce67f940da44f0033791dc137a
  mode: pip-vcs
# Used by t5x
airio:
  url: https://github.com/google/airio.git
  tracking_ref: main
  latest_verified_commit: 37109ff0d1059f885b9b11ef9058eca5d219d7cb
  mode: pip-vcs
clu:
  url: https://github.com/google/CommonLoopUtils.git
  tracking_ref: main
  latest_verified_commit: 307b0bc65ae2e2d801b6c19df2431c060a0aa4ec
  mode: pip-vcs
dllogger:
  url: https://github.com/NVIDIA/dllogger.git
  tracking_ref: master
  latest_verified_commit: 0540a43971f4a8a16693a9de9de73c1072020769
  mode: pip-vcs
jestimator:
  url: https://github.com/google-research/jestimator.git
  tracking_ref: main
  latest_verified_commit: 326824a477feef6d92e6f44175000907a72899ca
  mode: pip-vcs
optax:
  url: https://github.com/google-deepmind/optax.git
  tracking_ref: main
  latest_verified_commit: 831ddbf4fe9a0882f9d93c14bede25fef29d4bac
  mode: pip-vcs
seqio:
  url: https://github.com/google/seqio.git
  tracking_ref: main
  latest_verified_commit: 256819c6240d47dff7657b7f71a0049b5eb3aa9c
  mode: pip-vcs
# used by Pallas
openxla-triton:
  url: https://github.com/openxla/triton.git
  tracking_ref: llvm-head
  latest_verified_commit: 2aa35b6e9ddb4781bc3f3c38bd2b2fa97256adf5
  mode: git-clone
jax-triton:
  url: https://github.com/jax-ml/jax-triton.git
  tracking_ref: main
  latest_verified_commit: 859cc392bec876d132bd0790ea6c00b6c246dd2b
  mode: git-clone
maxtext:
  url: https://github.com/google/maxtext.git
  tracking_ref: main
  latest_verified_commit: 388901065cec51d56b5f1c824a56f7c432308692
  mode: git-clone
levanter:
  url: https://github.com/stanford-crfm/levanter.git
  tracking_ref: main
  latest_verified_commit: ab7dc65c267aba4ae39d2ea51fc64c05131b4221
  mode: git-clone
haliax:
  url: https://github.com/stanford-crfm/haliax.git
  tracking_ref: main
  latest_verified_commit: 81bbb7887704eeb0e016a47508ea8963f38686be
  mode: git-clone
mujoco:
  url: https://github.com/google-deepmind/mujoco.git
  tracking_ref: main
  latest_verified_commit: d4ca66a47b93df7f351ffecc0048f88ce850c302
  mode: git-clone
grain:
  # Used only in ARM t5x builds
  url: https://github.com/google/grain.git
  tracking_ref: main
  latest_verified_commit: 10fdd0dd4e684c847ae2d783c93d091b9ed44eea
  mode: git-clone
mujoco-mpc:
  url: https://github.com/google-deepmind/mujoco_mpc.git
  tracking_ref: main
  latest_verified_commit: 9bd2037498056a0ab9cf9463ab841e40fef54142
  mode: git-clone
language-to-reward-2023:
  url: https://github.com/google-deepmind/language_to_reward_2023.git
  tracking_ref: main
  latest_verified_commit: 4a3a20f9c8705e3a3ded4d218d9c129303d9682e
  mode: git-clone
mlperf-logging:
  url: https://github.com/mlcommons/logging.git
  tracking_ref: master
  latest_verified_commit: 8b8e048849691b2564e6487d108ab26fbae60541
  mode: pip-vcs
equinox:
  url: https://github.com/patrick-kidger/equinox.git
  tracking_ref: main
  latest_verified_commit: 36f81165d53328a9e83fc1dc67afc0dc25fa48ec
  mode: git-clone
grok-1:
  url: https://github.com/xai-org/grok-1.git
  tracking_ref: main
  latest_verified_commit: 7050ed204b8206bb8645c7b7bbef7252f79561b0
  mode: git-clone
